### ISSUE TITLE
gtlsxx28.dll missing from RPM package?

### ISSUE THREAD

**Issue by DavidMcKenna** [bitwiseworks/gnutls-os2#2]
While cleaning up some duplicate DLL's, I noticed that my old version of GNUtls (3.5.8 from Paul Smedley) has 3 DLL files:
gtls30.dll, gtlsos27.dll, and gtlsxx28.dll. The RPM of gnutls 3.6.12 from Netlabs only installs the first 2, but the 'debuginfo' rpm does install gtlsxx28.dbg as well. Was this intentional?

**Comment by SilvanScherrer** [comment]
Its not missing. Its just in the right package. Its in the c++ subpackage where it always belonged. If you cant find it please reopen the ticket again.

**Comment by DavidMcKenna** [comment]
Thanks for the tip. FYI - I found the gnutls-c++ RPM in the experimental directory, and was able to install with YUM, but for some reason neither it, nor gnutls-devel show up in ANPM...

**Comment by SilvanScherrer** [comment]
Hmm ANPM is not our business. So why its not shown i have no idea. If you want to know you need to ask them.
